// Barrel de tipos e DTOs compartilhados entre backend e frontend.
export * from './constants';
export * from './request/auth.request';
export * from './request/user.request';
export * from './request/customer.request';
export * from './request/vehicle.request';
export * from './request/service-order.request';
export * from './request/service-order-item.request';
export * from './request/maintenance-alert.request';
export * from './response/auth.response';
export * from './response/user.response';
export * from './response/customer.response';
export * from './response/vehicle.response';
export * from './response/service-order.response';
export * from './response/service-order-item.response';
export * from './response/fipe.response';
export * from './response/maintenance-alert.response';
export * from './response/pagination.response';
export * from './utils/case-convert';
