import type { CashFlowSummaryResponse, CompanySettingsResponse } from '@oficina/contracts';
import Image from 'next/image';
import { formatCurrencyBRL } from '@/lib/format-currency';

export function FinancialPrintDocument({ data, mode, month, company }: { data: CashFlowSummaryResponse; mode: 'report' | 'transactions'; month: string; company?: CompanySettingsResponse }) {
  const period = new Date(`${month}-02T12:00:00`).toLocaleDateString('pt-BR', { month: 'long', year: 'numeric' });
  const transactions = data.entries.filter((item) => item.status === 'PAID');
  const categoryRows = new Map<string, { income: number; expense: number }>();
  transactions.forEach((item) => { const row = categoryRows.get(item.categoryName) ?? { income: 0, expense: 0 }; row[item.type === 'INCOME' ? 'income' : 'expense'] += item.amountCents; categoryRows.set(item.categoryName, row); });
  return <article className="print-document mx-auto min-h-[273mm] max-w-[210mm] bg-white p-10 text-slate-950 shadow-lg">
    <header className="flex items-end justify-between border-b-2 border-slate-900 pb-4"><div className="flex items-start gap-3">{company?.logoDataUrl && <span className="flex size-12 shrink-0 items-center justify-center rounded bg-slate-900 p-1.5"><Image src={company.logoDataUrl} alt="" width={42} height={42} unoptimized className="size-full object-contain" /></span>}<div><p className="text-xs font-bold uppercase tracking-[0.16em] text-slate-500">{company?.name ?? 'Oficina'} · Financeiro</p><h1 className="mt-1 text-2xl font-bold">{mode === 'report' ? 'Relatório financeiro gerencial' : 'Movimentações financeiras'}</h1><p className="mt-1 text-sm capitalize text-slate-600">{period}</p></div></div><p className="text-right text-[10px] text-slate-500">Emitido em<br />{new Date().toLocaleString('pt-BR')}</p></header>
    {mode === 'report' && <><section className="print-break-inside-avoid mt-6 grid grid-cols-3 gap-3"><Summary label="Receitas realizadas" value={data.realizedIncomeCents} /><Summary label="Despesas realizadas" value={data.realizedExpenseCents} /><Summary label="Resultado do período" value={data.realizedBalanceCents} /></section><section className="mt-7"><h2 className="border-b border-slate-300 pb-2 text-sm font-bold uppercase tracking-wide">Resultado por categoria</h2><table className="mt-2 w-full border-collapse text-xs"><thead><tr className="bg-slate-100 text-left"><th className="p-2">Categoria</th><th className="p-2 text-right">Receitas</th><th className="p-2 text-right">Despesas</th><th className="p-2 text-right">Resultado</th></tr></thead><tbody>{[...categoryRows.entries()].map(([name, row]) => <tr key={name} className="border-b border-slate-200"><td className="p-2 font-semibold">{name}</td><td className="p-2 text-right">{formatCurrencyBRL(row.income)}</td><td className="p-2 text-right">{formatCurrencyBRL(row.expense)}</td><td className="p-2 text-right font-bold">{formatCurrencyBRL(row.income - row.expense)}</td></tr>)}</tbody></table></section><section className="print-break-inside-avoid mt-7 border-t-2 border-slate-900 pt-4"><div className="flex justify-between text-base font-bold"><span>Resultado realizado</span><span>{formatCurrencyBRL(data.realizedBalanceCents)}</span></div><div className="mt-2 flex justify-between text-xs text-slate-600"><span>Saldo projetado ao final do período</span><span>{formatCurrencyBRL(data.projectedBalanceCents)}</span></div></section></>}
    {mode === 'transactions' && <section className="mt-6"><table className="w-full border-collapse text-[10px]"><thead><tr className="bg-slate-900 text-left text-white"><th className="p-2">Data</th><th className="p-2">Descrição / parte</th><th className="p-2">Categoria</th><th className="p-2">Natureza</th><th className="p-2 text-right">Valor</th></tr></thead><tbody>{transactions.map((item) => <tr key={`${item.source}-${item.id}`} className="border-b border-slate-200"><td className="p-2">{new Date(item.paidAt ?? item.dueAt).toLocaleDateString('pt-BR')}</td><td className="p-2"><strong>{item.description}</strong>{(item.customerName || item.supplierName) && <div className="text-slate-500">{item.customerName ?? item.supplierName}</div>}</td><td className="p-2">{item.categoryName}</td><td className="p-2">{item.type === 'INCOME' ? 'Entrada' : 'Saída'}</td><td className="p-2 text-right font-bold">{item.type === 'INCOME' ? '+' : '−'} {formatCurrencyBRL(item.amountCents)}</td></tr>)}</tbody><tfoot><tr className="border-t-2 border-slate-900"><td colSpan={4} className="p-2 text-right font-bold">Saldo realizado</td><td className="p-2 text-right text-sm font-bold">{formatCurrencyBRL(data.realizedBalanceCents)}</td></tr></tfoot></table></section>}
    <footer className="mt-8 border-t border-slate-300 pt-3 text-[9px] text-slate-500">Documento gerencial emitido pelo sistema da oficina. Valores previstos não compõem o caixa realizado.</footer>
  </article>;
}
function Summary({ label, value }: { label: string; value: number }) { return <div className="border border-slate-300 p-3"><p className="text-[9px] font-bold uppercase text-slate-500">{label}</p><p className="mt-2 text-lg font-bold">{formatCurrencyBRL(value)}</p></div>; }
