'use client';

import { useMemo, useState } from 'react';
import type { FinancialEntryType } from '@oficina/contracts';
import { ArrowDownCircle, ArrowUpCircle, Check, Plus, Printer, Trash2 } from 'lucide-react';
import { toast } from 'sonner';
import { Button } from '@/components/ui/button';
import { Dialog, DialogContent, DialogFooter, DialogHeader, DialogTitle } from '@/components/ui/dialog';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import { Textarea } from '@/components/ui/textarea';
import { formatCurrencyBRL } from '@/lib/format-currency';
import { extractErrorMessage } from '@/lib/api/client';
import { hasPermission } from '@/features/auth/permissions';
import { useCustomersList } from '@/features/customers/hooks/use-customers';
import { useAuthStore } from '@/stores/auth-store';
import { useCashFlow, useCreateFinancialCategory, useCreateFinancialEntry, useDeleteFinancialCategory, useDeleteFinancialEntry, useFinancialCategories, useSettleFinancialEntry, useSuppliers } from '../hooks/use-financial';

type Mode = 'overview' | 'payables' | 'receivables' | 'cash-flow' | 'transactions' | 'categories' | 'reports';

export function FinancialWorkspace({ mode }: { mode: Mode }) {
  const user = useAuthStore((state) => state.user);
  const canManage = hasPermission(user, 'finance.manage');
  const [month, setMonth] = useState(new Date().toISOString().slice(0, 7));
  const startAt = `${month}-01T00:00:00.000Z`;
  const next = new Date(`${month}-01T00:00:00.000Z`); next.setUTCMonth(next.getUTCMonth() + 1);
  const flow = useCashFlow({ startAt, endAt: next.toISOString() });
  const categories = useFinancialCategories();
  const [entryOpen, setEntryOpen] = useState(false);
  const [categoryOpen, setCategoryOpen] = useState(false);

  if (flow.isLoading || categories.isLoading) return <div className="h-72 animate-pulse rounded-card bg-muted" />;
  if (!flow.data) return <div className="rounded-card border border-danger/30 bg-danger-subtle p-8 text-center text-danger">Não foi possível carregar os dados financeiros.</div>;
  const data = flow.data;

  return <div className="space-y-5">
    <header className="flex flex-col gap-3 border-b border-border pb-5 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-xs font-bold uppercase tracking-[0.14em] text-primary">Controle financeiro</p><h2 className="mt-1 text-2xl font-bold text-text">{MODE_TITLES[mode]}</h2><p className="mt-1 text-sm text-text-muted">{MODE_DESCRIPTIONS[mode]}</p></div><div className="flex flex-wrap gap-2"><Input className="w-40" type="month" value={month} onChange={(event) => setMonth(event.target.value)} />{(mode === 'transactions' || mode === 'reports') && <Button variant="outline" onClick={() => window.open(`/financial/print?mode=${mode === 'reports' ? 'report' : 'transactions'}&month=${month}`, '_blank', 'noopener,noreferrer')}><Printer className="size-4" />Imprimir</Button>}{canManage && ['payables', 'receivables', 'transactions'].includes(mode) && <Button onClick={() => setEntryOpen(true)}><Plus className="size-4" />Novo lançamento</Button>}{canManage && mode === 'categories' && <Button onClick={() => setCategoryOpen(true)}><Plus className="size-4" />Nova categoria</Button>}</div></header>

    {mode === 'overview' && <FinancialOverview data={data} />}
    {mode === 'cash-flow' && <CashFlow data={data} />}
    {mode === 'payables' && <Entries data={{ ...data, entries: data.entries.filter((entry) => entry.type === 'EXPENSE' && entry.status === 'PENDING') }} canManage={canManage} />}
    {mode === 'receivables' && <Entries data={{ ...data, entries: data.entries.filter((entry) => entry.type === 'INCOME' && entry.status === 'PENDING') }} canManage={canManage} />}
    {mode === 'transactions' && <Entries data={{ ...data, entries: data.entries.filter((entry) => entry.status === 'PAID') }} canManage={canManage} />}
    {mode === 'categories' && <Categories categories={categories.data?.categories ?? []} canManage={canManage} />}
    {mode === 'reports' && <Reports data={data} />}

    <EntryDialog open={entryOpen} onOpenChange={setEntryOpen} categories={categories.data?.categories ?? []} initialType={mode === 'receivables' ? 'INCOME' : 'EXPENSE'} lockType={mode === 'receivables' || mode === 'payables'} />
    <CategoryDialog open={categoryOpen} onOpenChange={setCategoryOpen} />
  </div>;
}

const MODE_TITLES = { overview: 'Visão financeira', payables: 'Contas a pagar', receivables: 'Contas a receber', 'cash-flow': 'Fluxo de caixa', transactions: 'Movimentações realizadas', categories: 'Categorias de receita e custo', reports: 'Relatórios financeiros' };
const MODE_DESCRIPTIONS = { overview: 'Resultado, compromissos e alertas do período em uma única leitura.', payables: 'Despesas previstas que ainda exigem pagamento.', receivables: 'Valores pendentes, incluindo parcelas originadas nas ordens de serviço.', 'cash-flow': 'Acompanhe a sequência das entradas, saídas e o saldo acumulado.', transactions: 'Extrato do que efetivamente entrou ou saiu do caixa.', categories: 'Organize a origem das receitas e o destino dos custos.', reports: 'Entenda onde o dinheiro entra, sai e forma o resultado.' };

type CashData = NonNullable<ReturnType<typeof useCashFlow>['data']>;

function FinancialOverview({ data }: { data: CashData }) {
  const overduePayables = data.entries.filter((item) => item.type === 'EXPENSE' && item.status === 'PENDING' && new Date(item.dueAt) < new Date()).length;
  const overdueReceivables = data.entries.filter((item) => item.type === 'INCOME' && item.status === 'PENDING' && new Date(item.dueAt) < new Date()).length;
  const margin = data.realizedIncomeCents ? Math.round((data.realizedBalanceCents / data.realizedIncomeCents) * 100) : 0;
  return <><section className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><Metric label="Receita realizada" value={data.realizedIncomeCents} positive /><Metric label="Despesa realizada" value={data.realizedExpenseCents} /><Metric label="Resultado do mês" value={data.realizedBalanceCents} positive={data.realizedBalanceCents >= 0} /><Metric label="Saldo projetado" value={data.projectedBalanceCents} positive={data.projectedBalanceCents >= 0} /></section><section className="grid gap-4 lg:grid-cols-[1.2fr_0.8fr]"><div className="rounded-card border border-border bg-card p-5 shadow-sm"><p className="text-xs font-bold uppercase tracking-wide text-text-muted">Leitura gerencial</p><div className="mt-4 grid grid-cols-3 gap-3"><Insight label="Margem do período" value={`${margin}%`} tone={margin >= 0 ? 'text-success' : 'text-danger'} /><Insight label="Contas a pagar vencidas" value={String(overduePayables)} tone={overduePayables ? 'text-danger' : 'text-success'} /><Insight label="Contas a receber vencidas" value={String(overdueReceivables)} tone={overdueReceivables ? 'text-warning' : 'text-success'} /></div></div><div className="rounded-card border border-border bg-card p-5 shadow-sm"><p className="text-sm font-bold text-text">Próximos compromissos</p><div className="mt-3 space-y-2">{data.entries.filter((item) => item.status === 'PENDING').slice(0, 4).map((item) => <div key={item.id} className="flex justify-between gap-3 text-sm"><span className="truncate text-text-muted">{item.description}</span><strong className={item.type === 'INCOME' ? 'text-success' : 'text-danger'}>{formatCurrencyBRL(item.amountCents)}</strong></div>)}{!data.entries.some((item) => item.status === 'PENDING') && <p className="text-sm text-text-muted">Nenhum compromisso previsto.</p>}</div></div></section></>;
}
function Insight({ label, value, tone }: { label: string; value: string; tone: string }) { return <div><p className={`text-2xl font-bold ${tone}`}>{value}</p><p className="mt-1 text-xs text-text-muted">{label}</p></div>; }

function CashFlow({ data }: { data: CashData }) {
  let runningBalance = 0;
  const rows = data.entries.map((entry) => { runningBalance += entry.type === 'INCOME' ? entry.amountCents : -entry.amountCents; return { ...entry, runningBalance }; });
  return <><section className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><Metric label="Entradas realizadas" value={data.realizedIncomeCents} positive /><Metric label="Saídas realizadas" value={data.realizedExpenseCents} /><Metric label="Saldo realizado" value={data.realizedBalanceCents} positive={data.realizedBalanceCents >= 0} /><Metric label="Saldo projetado" value={data.projectedBalanceCents} positive={data.projectedBalanceCents >= 0} /></section><section className="overflow-x-auto rounded-card border border-border bg-card shadow-sm"><div className="grid min-w-[650px] grid-cols-[110px_1fr_130px_130px] gap-3 border-b border-border bg-muted/50 px-4 py-3 text-xs font-bold uppercase text-text-muted"><span>Data</span><span>Movimento</span><span className="text-right">Valor</span><span className="text-right">Saldo acumulado</span></div>{rows.map((entry) => <div key={`${entry.source}-${entry.id}`} className="grid min-w-[650px] grid-cols-[110px_1fr_130px_130px] gap-3 border-b border-border px-4 py-3 text-sm"><span className="text-text-muted">{new Date(entry.dueAt).toLocaleDateString('pt-BR')}</span><div><p className="font-semibold">{entry.description}</p><p className="text-xs text-text-muted">{entry.status === 'PAID' ? 'Realizado' : 'Previsto'}</p></div><strong className={`text-right ${entry.type === 'INCOME' ? 'text-success' : 'text-danger'}`}>{entry.type === 'INCOME' ? '+' : '−'} {formatCurrencyBRL(entry.amountCents)}</strong><strong className={`text-right ${entry.runningBalance >= 0 ? 'text-text' : 'text-danger'}`}>{formatCurrencyBRL(entry.runningBalance)}</strong></div>)}</section></>;
}
function Metric({ label, value, positive }: { label: string; value: number; positive?: boolean }) { return <div className="rounded-card border border-border bg-card p-5 shadow-sm"><p className="text-xs font-bold uppercase tracking-wide text-text-muted">{label}</p><p className={`mt-3 text-2xl font-bold ${positive ? 'text-success' : value < 0 ? 'text-danger' : 'text-text'}`}>{formatCurrencyBRL(value)}</p></div>; }

function Entries({ data, canManage, compact }: { data: CashData; canManage: boolean; compact?: boolean }) {
  const settle = useSettleFinancialEntry(); const remove = useDeleteFinancialEntry();
  return <section className="overflow-x-auto rounded-card border border-border bg-card shadow-sm"><div className="grid min-w-[680px] grid-cols-[110px_1fr_130px_120px_auto] gap-3 border-b border-border bg-muted/50 px-4 py-3 text-xs font-bold uppercase text-text-muted"><span>Data</span><span>Descrição</span><span>Categoria</span><span className="text-right">Valor</span><span /></div><div className="min-w-[680px] divide-y divide-border">{data.entries.map((entry) => <div key={`${entry.source}-${entry.id}`} className="grid grid-cols-[110px_1fr_130px_120px_auto] items-center gap-3 px-4 py-3 text-sm"><span className="text-text-muted">{new Date(entry.dueAt).toLocaleDateString('pt-BR')}</span><div><p className="font-semibold text-text">{entry.description}</p><p className="text-xs text-text-muted">{entry.status === 'PAID' ? 'Realizado' : 'Previsto'}{entry.supplierName ? ` · ${entry.supplierName}` : ''}{entry.source === 'SERVICE_ORDER' ? ' · automático da OS' : ''}</p></div><span className="truncate text-text-muted">{entry.categoryName}</span><strong className={`text-right ${entry.type === 'INCOME' ? 'text-success' : 'text-danger'}`}>{entry.type === 'INCOME' ? '+' : '−'} {formatCurrencyBRL(entry.amountCents)}</strong><div className="flex justify-end gap-1">{canManage && entry.source === 'MANUAL' && entry.status === 'PENDING' && <Button variant="ghost" size="icon" aria-label="Marcar como pago" onClick={() => settle.mutate(entry.id)}><Check className="size-4" /></Button>}{canManage && entry.source === 'MANUAL' && <Button variant="ghost" size="icon" className="text-danger" aria-label="Excluir lançamento" onClick={() => remove.mutate(entry.id)}><Trash2 className="size-4" /></Button>}</div></div>)}{data.entries.length === 0 && <p className="p-10 text-center text-sm text-text-muted">Nenhum lançamento no período.</p>}</div>{compact && <div className="border-t border-border px-4 py-3 text-xs text-text-muted">Recebimentos de OS são incluídos automaticamente.</div>}</section>;
}

function Categories({ categories, canManage }: { categories: NonNullable<ReturnType<typeof useFinancialCategories>['data']>['categories']; canManage: boolean }) {
  const remove = useDeleteFinancialCategory();
  return <div className="grid gap-4 lg:grid-cols-2">{(['INCOME', 'EXPENSE'] as const).map((type) => {
    const typeCategories = categories.filter((item) => item.type === type);
    const groups = [...new Set(typeCategories.map((item) => item.group))];
    return <section key={type} className="rounded-card border border-border bg-card p-5 shadow-sm"><div className="flex items-center gap-2">{type === 'INCOME' ? <ArrowUpCircle className="text-success" /> : <ArrowDownCircle className="text-danger" />}<h3 className="font-bold text-text">{type === 'INCOME' ? 'Categorias de receita' : 'Categorias de custo'}</h3></div><div className="mt-5 space-y-5">{groups.map((group) => <div key={group}><p className="border-b border-border pb-2 text-xs font-bold uppercase tracking-wide text-text-muted">{group}</p><div className="divide-y divide-border">{typeCategories.filter((item) => item.group === group).map((item) => <div key={item.id} className="flex items-center justify-between py-2.5"><span className="flex items-center gap-2 text-sm font-semibold"><span className="size-2 rounded-full" style={{ backgroundColor: item.color ?? '#64748B' }} />{item.name}</span>{canManage && !item.isSystem && <Button variant="ghost" size="icon" className="text-danger" onClick={() => remove.mutate(item.id, { onError: (error) => toast.error(extractErrorMessage(error)) })}><Trash2 className="size-4" /></Button>}</div>)}</div></div>)}{groups.length === 0 && <p className="py-6 text-center text-sm text-text-muted">Nenhuma categoria cadastrada.</p>}</div></section>;
  })}</div>;
}

function Reports({ data }: { data: CashData }) {
  const rows = useMemo(() => { const map = new Map<string, { income: number; expense: number }>(); data.entries.filter((item) => item.status === 'PAID').forEach((item) => { const row = map.get(item.categoryName) ?? { income: 0, expense: 0 }; row[item.type === 'INCOME' ? 'income' : 'expense'] += item.amountCents; map.set(item.categoryName, row); }); return [...map.entries()]; }, [data.entries]);
  return <div className="grid gap-5 xl:grid-cols-[0.7fr_1.3fr]"><section className="rounded-card border border-border bg-card p-5 shadow-sm"><p className="text-xs font-bold uppercase tracking-wide text-text-muted">DRE gerencial simplificada</p><div className="mt-5 space-y-4"><ReportLine label="Receita realizada" value={data.realizedIncomeCents} /><ReportLine label="(−) Custos e despesas" value={-data.realizedExpenseCents} /><div className="border-t border-border pt-4"><ReportLine label="Resultado do período" value={data.realizedBalanceCents} strong /></div></div><p className="mt-5 text-xs leading-5 text-text-muted">Resultado pelo regime de caixa. Custos de peças ainda dependem do lançamento da despesa de aquisição.</p></section><section className="rounded-card border border-border bg-card p-5 shadow-sm"><h3 className="font-bold text-text">Resultado realizado por categoria</h3><div className="mt-4 divide-y divide-border">{rows.map(([name, values]) => <div key={name} className="grid grid-cols-[1fr_140px_140px] gap-3 py-3 text-sm"><strong>{name}</strong><span className="text-right text-success">{formatCurrencyBRL(values.income)}</span><span className="text-right text-danger">{formatCurrencyBRL(values.expense)}</span></div>)}{rows.length === 0 && <p className="py-10 text-center text-sm text-text-muted">Sem movimentos realizados no período.</p>}</div></section></div>;
}
function ReportLine({ label, value, strong }: { label: string; value: number; strong?: boolean }) { return <div className={`flex items-center justify-between gap-3 ${strong ? 'text-base font-bold' : 'text-sm'}`}><span>{label}</span><span className={value < 0 ? 'text-danger' : strong ? 'text-success' : 'text-text'}>{formatCurrencyBRL(value)}</span></div>; }

function EntryDialog({ open, onOpenChange, categories, initialType, lockType }: { open: boolean; onOpenChange: (open: boolean) => void; categories: NonNullable<ReturnType<typeof useFinancialCategories>['data']>['categories']; initialType: FinancialEntryType; lockType: boolean }) {
  const create = useCreateFinancialEntry(); const suppliers = useSuppliers(); const [type, setTypeState] = useState<FinancialEntryType>(initialType); const customers = useCustomersList({ offset: 0, limit: 100 }, { enabled: type === 'INCOME' }); const setType = (value: FinancialEntryType) => { if (!lockType) setTypeState(value); }; const [categoryId, setCategoryId] = useState(''); const [supplierId, setSupplierId] = useState(''); const [customerId, setCustomerId] = useState(''); const [description, setDescription] = useState(''); const [amount, setAmount] = useState(''); const [dueAt, setDueAt] = useState(new Date().toISOString().slice(0, 10)); const [status, setStatus] = useState<'PENDING' | 'PAID'>('PENDING'); const [notes, setNotes] = useState('');
  const submit = () => { const amountCents = Math.round(Number(amount.replace(',', '.')) * 100); if (!categoryId || !description.trim() || amountCents <= 0) return toast.error('Preencha categoria, descrição e valor.'); if (type === 'EXPENSE' && !supplierId) return toast.error('Selecione o fornecedor.'); if (type === 'INCOME' && !customerId) return toast.error('Selecione o cliente.'); create.mutate({ categoryId, supplierId: type === 'EXPENSE' ? supplierId : undefined, customerId: type === 'INCOME' ? customerId : undefined, type, description, amountCents, dueAt: new Date(`${dueAt}T12:00:00`).toISOString(), status, notes: notes || undefined }, { onSuccess: () => { toast.success('Lançamento criado.'); onOpenChange(false); }, onError: (error) => toast.error(extractErrorMessage(error)) }); };
  return <Dialog open={open} onOpenChange={onOpenChange}><DialogContent><DialogHeader><DialogTitle>Novo lançamento</DialogTitle></DialogHeader><div className="grid gap-4 sm:grid-cols-2"><Field label="Natureza"><Select value={type} onValueChange={(value) => { setType(value as FinancialEntryType); setCategoryId(''); setSupplierId(''); setCustomerId(''); }}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent><SelectItem value="INCOME">Receita</SelectItem><SelectItem value="EXPENSE">Despesa</SelectItem></SelectContent></Select></Field><Field label="Categoria"><Select value={categoryId} onValueChange={setCategoryId}><SelectTrigger><SelectValue placeholder="Selecione" /></SelectTrigger><SelectContent>{categories.filter((item) => item.type === type).map((item) => <SelectItem key={item.id} value={item.id}>{item.name}</SelectItem>)}</SelectContent></Select></Field>{type === 'EXPENSE' && <div className="sm:col-span-2"><Field label="Fornecedor"><Select value={supplierId} onValueChange={setSupplierId}><SelectTrigger><SelectValue placeholder="Selecione o fornecedor" /></SelectTrigger><SelectContent>{suppliers.data?.suppliers.filter((item) => item.status === 'ACTIVE').map((item) => <SelectItem key={item.id} value={item.id}>{item.name}</SelectItem>)}</SelectContent></Select></Field>{(suppliers.data?.suppliers.length ?? 0) === 0 && <p className="mt-1 text-xs text-warning">Cadastre um fornecedor no submenu Financeiro antes de lançar a conta.</p>}</div>}{type === 'INCOME' && <div className="sm:col-span-2"><Field label="Cliente"><Select value={customerId} onValueChange={setCustomerId}><SelectTrigger><SelectValue placeholder="Selecione o cliente" /></SelectTrigger><SelectContent>{customers.data?.items.map((item) => <SelectItem key={item.id} value={item.id}>{item.name} · {item.document}</SelectItem>)}</SelectContent></Select></Field>{(customers.data?.items.length ?? 0) === 0 && <p className="mt-1 text-xs text-warning">Cadastre o cliente no menu Clientes antes de lançar a conta.</p>}</div>}<Field label="Descrição"><Input value={description} onChange={(e) => setDescription(e.target.value)} /></Field><Field label="Valor"><Input inputMode="decimal" value={amount} onChange={(e) => setAmount(e.target.value)} /></Field><Field label="Vencimento"><Input type="date" value={dueAt} onChange={(e) => setDueAt(e.target.value)} /></Field><Field label="Situação"><Select value={status} onValueChange={(value) => setStatus(value as 'PENDING' | 'PAID')}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent><SelectItem value="PENDING">Previsto</SelectItem><SelectItem value="PAID">Realizado</SelectItem></SelectContent></Select></Field><div className="sm:col-span-2"><Field label="Observação"><Textarea value={notes} onChange={(e) => setNotes(e.target.value)} /></Field></div></div><DialogFooter><Button onClick={submit} disabled={create.isPending}>Salvar lançamento</Button></DialogFooter></DialogContent></Dialog>;
}
function CategoryDialog({ open, onOpenChange }: { open: boolean; onOpenChange: (open: boolean) => void }) { const create = useCreateFinancialCategory(); const [name, setName] = useState(''); const [type, setType] = useState<FinancialEntryType>('EXPENSE'); return <Dialog open={open} onOpenChange={onOpenChange}><DialogContent><DialogHeader><DialogTitle>Nova categoria</DialogTitle></DialogHeader><Field label="Nome"><Input value={name} onChange={(e) => setName(e.target.value)} /></Field><Field label="Natureza"><Select value={type} onValueChange={(value) => setType(value as FinancialEntryType)}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent><SelectItem value="INCOME">Receita</SelectItem><SelectItem value="EXPENSE">Custo/despesa</SelectItem></SelectContent></Select></Field><DialogFooter><Button onClick={() => create.mutate({ name, type }, { onSuccess: () => { toast.success('Categoria criada.'); setName(''); onOpenChange(false); }, onError: (error) => toast.error(extractErrorMessage(error)) })}>Criar categoria</Button></DialogFooter></DialogContent></Dialog>; }
function Field({ label, children }: { label: string; children: React.ReactNode }) { return <div className="space-y-2"><Label>{label}</Label>{children}</div>; }
